apiVersion: v1
kind: Service
metadata:
  name: personal-finance-dashboard
  namespace: personal-finance-dashboard
spec:
  selector:
    app: personal-finance-dashboard
  ports:
    - port: 80
      targetPort: 8501
